name: Omnibus Consulting
favicon: null
layout_spectrum: 0.53281
typography_spectrum: 0.56948661361821
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#848484'
    - '#636466'
    - '#3f3f3f'
    - '#c9c8cd'
  brandStrength: 0.9718918490689248
  lightness: 0.2575893262401223
  saturation: 0.7070771316066384
  rhythmicContrast: 0.9447867458220571
purpose: []
